version: "3.7"
services:
  app:
    image: bastyje/pamiw-angular:1.0
    restart: always
    networks:
      pamiw-net:
        ipv4_address: 10.0.0.3
  api:
    image: bastyje/pamiw-net:1.0
    networks:
      pamiw-net:
        ipv4_address: 10.0.0.2
      pamiw-internal-net:
        ipv4_address: 10.0.1.2
    working_dir: /App
  mssql:
    image: bastyje/pamiw-database:1.0
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    networks:
      pamiw-internal-net:
        ipv4_address: 10.0.1.3
networks:
  pamiw-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
  pamiw-internal-net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.1.0/29
