version: "3.7"
services:
  api:
    build:
      context: ./net
      dockerfile: ../docker/net/Dockerfile
    links:
      - "mssql:database"
    ports:
      - 8081:80
      - 8082:443
    working_dir: /app
  mssql:
    build:
      context: ./database
      dockerfile: ../docker/database/Dockerfile
    volumes: 
      - db:/var/opt/mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1435:1433
volumes:
  db:
    driver: local
